import Head from 'next/head'
import {
  getDatabase,
  ref,
  onChildAdded,
  onChildChanged,
  onChildRemoved
} from 'firebase/database'
import className from '../styles/pagination.module.css'
import { useEffect, useRef, useState } from 'react'
import { database } from '../services/firebase-sdk'

const ChildEvents = () => {
  // const [shop, setShop] = useState([])
  const tableBodyRef = useRef(null)

  const listenChildEvents = () => {
    const shopRef = ref(database, 'shop')

    onChildAdded(shopRef, (data) => {
      const tr = document.createElement('tr')
      const td = document.createElement('td')
      const text = document.createTextNode(data.val().name)
      td.appendChild(text)
      tr.appendChild(td)
      tableBodyRef.current.appendChild(tr)
      console.log({ key: data.key, values: data.val() })
    })

    // onChildChanged(shopRef, (data) => {
    //   console.log({ key: data.key, values: data.val() })
    // })

    // onChildRemoved(shopRef, (data) => {
    //   console.log({ key: data.key, values: data.val() })
    // })
  }

  useEffect(() => {
    listenChildEvents()
  }, [])

  return (
    <div>
      <Head>
        <title>Child Events</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={className.container}>
        <table>
          <thead>
            <tr className={className['table-head-row']}>
              <th className={className['table-head-cell']}>Key</th>
              <th className={className['table-head-cell']}>Address</th>
              <th className={className['table-head-cell']}>Name</th>
              <th className={className['table-head-cell']}>Index</th>
            </tr>
          </thead>
          <tbody ref={tableBodyRef}></tbody>
        </table>
      </div>
    </div>
  )
}

export default ChildEvents
