import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useGetValue from '../hooks/useGetValue'

const Home = () => {
  const posts = useGetValue('posts')

  console.log(posts)

  const isLoading = posts.isLoading

  // if (isLoading) {
  //   return <p>Fetching data...</p>
  // }

  // const dataPosts = Object.values(posts.snapshot)
  // const dataUsers = Object.values(users.snapshot)

  // console.log({ dataPosts, dataUsers })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isLoading && <h4>Fetching data...</h4>}
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <button
          onClick={posts.getValueLater}
          style={{ background: 'red', padding: 8 }}
        >
          Get Value later
        </button>
        {/* <div>
          {dataPosts.map((item) => {
            return (
              <div key={item.title}>
                <h2>{item.title}</h2>
                <p>{item.content}</p>
              </div>
            )
          })}
        </div> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
