import Head from 'next/head'
import {
  get,
  ref
} from 'firebase/database'
import className from '../styles/pagination.module.css'
import { clientABCDatabase } from '../services/firebase-sdk'
import { useEffect } from 'react'

export const getValues = async (path) => {
  const dbRef = ref(clientABCDatabase, path)
  const dbGet = await get(dbRef)
  const dbValue = dbGet.val()
  return dbValue
}

const MultipleDatabase = () => {
  const getUsersABC = async () => {
    const users = await getValues('users')
    console.log(users)
  }

  useEffect(() => {
    getUsersABC()
  }, [])

  return (
    <div>
      <Head>
        <title>Multiple Databases Pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={className.container}>
        <h1 style={{ fontSize: '5rem' }}>Multiple Databases Pages</h1>
      </div>
    </div>
  )
}

export default MultipleDatabase
