import Head from 'next/head'
import { get, ref, query, orderByChild, equalTo } from 'firebase/database'
import { useEffect } from 'react'
import className from '../styles/pagination.module.css'
import { database } from '../services/firebase-sdk'

const getValues = async (path) => {
  const dbRef = ref(database, path)
  const dbGet = await get(dbRef)
  const dbValue = dbGet.val()
  return dbValue
}

const getQuery = async (path, child, queries) => {
  const dbRef = ref(database, path)
  const dbQuery = query(dbRef, orderByChild(child), ...queries)
  const dbGet = await get(dbQuery)
  const dbValue = dbGet.val()
  return dbValue
}

const RelationPage = () => {
  const getData = async () => {
    const user = await getValues('users/adH8GE92Y2TpeCF2cs11C13IVB42')
    const profile = await getValues('profile/adH8GE92Y2TpeCF2cs11C13IVB42')
    // const posts = await getValues('posts/adH8GE92Y2TpeCF2cs11C13IVB42')
    // const posts = await getQuery('posts2', 'userId', [
    //   equalTo('adH8GE92Y2TpeCF2cs11C13IVB42')
    // ])
    const postsTags = await getQuery('posts_tags', 'postId', [
      equalTo('cl98h87fw000009l49cwcf2s9')
    ])
    const tag1 = await getValues('tags/cl98iurtk000m09labp6wghmz')
    const tag2 = await getValues('tags/cl98ivljs000n09la55hn65ld')

    console.log({ posts, postsTags, tag1, tag2 })

    const technologyPosts = await getQuery('posts_tags', 'tagId', [
      equalTo('cl98iurtk000m09labp6wghmz')
    ])

    const posts = await getValues('posts2/cl98h87fw000009l49cwcf2s9')

    console.log({technologyPosts, posts})




  }

  useEffect(() => {
    getData()
  }, [])

  return (
    <div>
      <Head>
        <title>Relation Pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={className.container}>
        <h1 style={{ fontSize: '5rem' }}>Relation Pages</h1>
      </div>
    </div>
  )
}

export default RelationPage
