import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useRemoveValue from '../hooks/useRemoveValue'

const Home = () => {
  const removePost = useRemoveValue('products/-N7W-w4cGdfPjx8GVk7w')
  console.log(removePost)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <button
          onClick={() => removePost.withSet()}
          style={{ background: 'red', padding: 8 }}
        >
          Remove post by set method
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
