import Head from 'next/head'
import { useEffect, useState } from 'react'
import { equalTo } from 'firebase/database'
import className from '../styles/pagination.module.css'
import {
  authStateChange,
  signIn,
  signOut,
  getValues,
  createValue,
  getQuery
} from '../modules/firebase'

const RulesPage = () => {
  const [user, setUser] = useState(null)

  const onAuth = (user) => {
    console.log('User is signed in')
    setUser(user)
  }

  const onNoAuth = () => {
    console.log('User is not signed in')
    setUser(null)
  }

  const onReadData = async () => {
    const values = await getValues('users')
    console.log(values)
  }

  const onCreateData = async () => {
    const path = 'posts'
    const values = {
      title: 123455,
      body: 'Body post pertama',
      uid: user?.uid
    }
    await createValue(path, values)
  }

  const onQueryData = async () => {
    const data = await getQuery('posts', 'title', [
      equalTo('Editing Post Yang uid sama')
    ])

    console.log(data)
  }

  useEffect(() => {
    authStateChange(onAuth, onNoAuth)
  }, [])

  useEffect(() => {
    console.log(user)
  }, [user])

  return (
    <div>
      <Head>
        <title>Rules Pages</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={className.container}>
        <h1 style={{ fontSize: '5rem' }}>Rules Pages</h1>
        <div style={{ display: 'flex', gap: 12 }}>
          <button onClick={() => signIn('erdecode@yahoo.com', '12345678')}>
            Sign in
          </button>
          <button onClick={signOut}>Sign out</button>
          <button onClick={onReadData}>Read Data</button>
          <button onClick={onCreateData}>Create Data</button>
          <button onClick={onQueryData}>Query Data</button>
        </div>
      </div>
    </div>
  )
}

export default RulesPage
