import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import useUpdateValue from '../hooks/useUpdateValue'

const Home = () => {
  const updateAPost = useUpdateValue()
  const update = useUpdateValue()

  const updatePost = async () => {
    const path = '/posts'
    const value = {
      createdAt: new Date(),
      updatedAt: new Date(),
      categories: 'Life'
    }

    await updateAPost.updateDoc(path, value)
  }

  const updateCartAndProduct = async () => {
    const updatesAll = {
      'cart': 'Karpet Luar biasa ajaib',
      'products/-N7W-tnykgzuMGwx4L7y/price': '2500000',
      'products/-N7W-tnykgzuMGwx4L7y/timestamp': Date.now(),
    }

    await update.updateField(updatesAll)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* {isLoading && <h4>Fetching data...</h4>} */}
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <button onClick={updatePost} style={{ background: 'red', padding: 8 }}>
          Update Doc
        </button>
        {/* <button
          onClick={updateCartAndProduct}
          style={{ background: 'blue', padding: 8 }}
        >
          Update Field
        </button> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
