import Head from 'next/head'
import { ref, onValue } from 'firebase/database'
import className from '../styles/pagination.module.css'
import { database } from '../services/firebase-sdk'
import { useEffect, useState } from 'react'

const ValueEvents = () => {
  const [shop, setShop] = useState({})
  console.log(shop)

  const listenValueEvents = () => {
    const shopRef = ref(database, 'shop/cl7ptog6c000009li95gwdwtd')

    onValue(
      shopRef,
      (snapshot) => {
        // const newShop = []
        // snapshot.forEach((childSnapshot) => {
        //   const childKey = childSnapshot.key
        //   const childData = childSnapshot.val()
        //   newShop.push({ key: childKey, ...childData })
        // })
        setShop({ key: snapshot.key, ...snapshot.val() })
      }
    )
  }

  useEffect(() => {
    listenValueEvents()
  }, [])

  return (
    <div>
      <Head>
        <title>Value Events</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={className.container}>
        <div>
          <h4>Key</h4>
          <p>{shop.key}</p>
        </div>
        <div>
          <h4>Address</h4>
          <p>{shop.address}</p>
        </div>
        <div>
          <h4>Name</h4>
          <p>{shop.name}</p>
        </div>
        <div>
          <h4>Index</h4>
          <p>{shop.number}</p>
        </div>
        <table>
          <thead>
            <tr className={className['table-head-row']}>
              <th className={className['table-head-cell']}>Key</th>
              <th className={className['table-head-cell']}>Address</th>
              <th className={className['table-head-cell']}>Name</th>
              <th className={className['table-head-cell']}>Index</th>
            </tr>
          </thead>
          {/* <tbody>
            {shop.map((item) => {
              return (
                <tr key={item.key} className={className['table-body-row']}>
                  <th className={className['table-body-cell']}>{item.key}</th>
                  <th className={className['table-body-cell']}>{item.address}</th>
                  <th className={className['table-body-cell']}>{item.name}</th>
                  <th className={className['table-body-cell']}>{item.number}</th>
                </tr>
              )
            })}
          </tbody> */}
        </table>
      </div>
    </div>
  )
}

export default ValueEvents
